### ISSUE TITLE
Promote no-extra-parens to a warning

### ISSUE THREAD

**Issue by niedzielski** [wikimedia/eslint-config-node-services#14]
Extra parentheses can be useful to clarify complex logic but can equally become detrimental to readability when used without reason. I posit that it's better to assume unintentional error, often due to code changes, when unnecessary parentheses appear and we should flag them as a warning unless explicitly disabled.

Consider the following example which passes in the current lint configuration:

```js
function(el) {
  while ((el = el.parentElement)) {
    // ...
  }
}
```

With [`no-extra-parens`](http://eslint.org/docs/rules/no-extra-parens) promoted to a warning level, the above code would be flagged as warning and devs would be necourage to write:

```js
function(el) {
  while (el = el.parentElement) {
    // ...
  }
}
```

**Comment by Pchelolo** [comment]
Why warning level? In case they're used intentionally, a warning would be quite annoying, so I think we should discourage using them completely with error level. Individual service developers, if want, can overwrite the rule in the service config.

**Comment by niedzielski** [comment]
They're actually [currently disabled](https://github.com/wikimedia/eslint-config-node-services/blob/master/.eslintrc.js#L44) so promoting to either warning or error would be an improvement in my mind. In general, I think style concerns that are unlikely to cause a bug by misconception should appear as warnings and more insidious and subtle violations should be errors. e.g., a warning might be too many newlines and an error might be using `==` instead of `===`. My editor, Visual Studio Code, actually colors warnings as green and errors as red, so it's super easy to spot the functional bugs in a file and the command line usage of ESLint is similar. For this case specifically, I think adding one or two extra parentheses is unlikely to cause a misconception so it's a warning in my book. This [patch](https://github.com/wikimedia/eslint-config-node-services/pull/8/files#diff-0295c552606a5a4c45c54c5662f801d4R2) provides users a command line client that forbids even warnings from passing lint (e.g., as part of a pre-commit hook) so you get no lint at commit time but pure style nitpicks are permitted during development time.

**Comment by Pchelolo** [comment]
@niedzielski Created a PR. I've gave you the write access to this repo so that you could not wait for me to get to look at it and go ahead on minor changes. What's your npm username I'll add you there as well.

**Comment by niedzielski** [comment]
@Pchelolo, yay! I'm `niedzielski` on NPM.
