### ISSUE TITLE
extend eslint-config-wikimedia

### ISSUE THREAD

**Issue by edg2s** [wikimedia/eslint-config-node-services#17]
This would remove a bunch of duplication on things we currently agree on, highlight were the difference are, and prevent further divergence.

**Comment by edg2s** [comment]
Copy @Pchelolo's comment from the PR
> Overall I like the idea. There will be some differences anyway because the wikimedia config is mainly focused on the frontend code while this one is for backend code, but it's good to bring them as close as possible.

**Comment by edg2s** [comment]
I think there are some rules which are environment-specific, for example "no-var", but for purely stylistic rules it would be good if they slowly converged.

**Comment by Pchelolo** [comment]
Published as eslint-config-node-services@2.2.0

**Comment by jdforrester** [comment]
Ha. Duplicate of #2.
