### ISSUE TITLE
Turn off the radix "as-needed" rule?

### ISSUE THREAD

**Issue by mdholloway** [wikimedia/eslint-config-node-services#3]
In running eslint on mobileapps, we identified one spot where, to err on the conservative side, we'd prefer to specify a decimal radix for parseInt, but the "as-needed" radix rule forbids it.  It's in the context of date string processing, where leading zeroes are relevant.

Discussion is here: https://gerrit.wikimedia.org/r/#/c/324005/1/lib/dateUtil.js

I can see a case for allowing the decimal radix to be omitted, but why forbid it across the board?

**Comment by niedzielski** [comment]
We can add an eslint line ignore but wouldn't it be safer to use `always` instead?

**Comment by Pchelolo** [comment]
Sounds reasonable. Better not to ignore anything but tweak the config instead, so PR is welcome
